apiVersion: v1
kind: List
items:

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: auth-delegator-openshift-namespace-reservation
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    namespace: openshift-namespace-reservation
    name: server

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: system:openshift:online:namespace-reservation-server
  rules:
  - apiGroups:
    - online.openshift.io
    resources:
    - namespacereservations
    verbs:
    - get
    - list
    - watch

# to let aggregated apiservers create admission reviews
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: system:openshift:online:namespace-reservation-requester
  rules:
  - apiGroups:
    - admission.online.openshift.io
    resources:
    - namespacereservations
    verbs:
    - create

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: namespace-reservation-server-openshift-namespace-reservation
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:openshift:online:namespace-reservation-server
  subjects:
  - kind: ServiceAccount
    namespace: openshift-namespace-reservation
    name: server

# to read the config for terminating authentication
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: kube-system
    name: extension-server-authentication-reader-openshift-namespace-reservation
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    namespace: openshift-namespace-reservation
    name: server

# this should be a default for an aggregated apiserver
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: should-be-default-for-aggregated-apiserver
  rules:
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch

# this should be a default for an aggregated apiserver
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: should-be-default-for-aggregated-apiserver
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: should-be-default-for-aggregated-apiserver
  subjects:
  - kind: ServiceAccount
    namespace: openshift-namespace-reservation
    name: server
